from . import estimation_team
from . import inspection_team
from . import engineering_team
from . import production_team
from . import qa_qc_team
from . import installation_team
from . import project_project
from . import hr_job
from . import product_product
from . import stock_move
from . import sale_order
from . import project_task
from . import crm_lead
from . import res_company
from . import res_partner
from . import boq_material
from . import hr_payslip
from . import approve_sales_terms
from . import hr_employee
from . import project_planning
from . import mrp_production
from . import account_move
from . import material_request
from . import shop_drawing_line
from . import purchase_order
from . import project_delivery

