# -*- coding: utf-8 -*-
{
    'name': 'ARM Customization',
    'version': '17.0.1.2.9',
    'category': 'Sales/CRM',
    'summary': 'ARM Customization',
    'description': 'crm project customization',
    'depends': [
        'crm', 'project', 'hr', 'hr_recruitment', 'sale_management', 'stock', 'purchase', 'account', 'hr_timesheet',
        'hr_payroll_community',
        'project_task_default_stage', 'stock_analytic', 'base_account_budget', 'base_accounting_kit',
        'defferd_revenue_account',
        'pdc_payment', 'stock_analytic', 'mrp'
    ],
    'data': [
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'security/res_group.xml',
        'security/ir.model.access.csv',
        'views/project_project.xml',
        'views/product_product.xml',
        'views/res_company.xml',
        'views/res_partner.xml',
        'views/hr_employee.xml',
        'views/hr_job.xml',
        'views/hr_payslip.xml',
        'views/sale_order.xml',
        'views/stock_move.xml',
        'views/project_task.xml',
        'views/cost_enter_view.xml',
        'views/crm_lead.xml',
        'views/mrp_production.xml',
        'views/estimation_team.xml',
        'views/engineering_team.xml',
        'views/inspection_team.xml',
        'views/installation_team.xml',
        'views/production_team.xml',
        'views/approve_sales_team.xml',
        'views/qa_qc_team.xml',
        'views/project_planning.xml',
        'views/active_project.xml',
        # 'views/qa_qc_menu.xml',
        'views/account_move.xml',
        'views/purchase_order.xml',
        'views/delivered_menu.xml',
        'views/project_delivery.xml',
        'views/delivery_note_report.xml',
        'views/account_payment.xml',
        'views/material_request.xml',
        'wizard/estimation_refuse_reason.xml',
        'wizard/project_task_assign_wizard.xml',
        'wizard/bulk_item_upload.xml',
        'wizard/bulk_item_upload_task.xml',
        'wizard/sale_approve_wizard.xml',
        'wizard/refuse_reason.xml',
        'wizard/assemble_upload_item.xml',
        'wizard/progress_invoice_creation_wizard.xml',
        'wizard/material_requisition_wizard.xml',
        'wizard/shop_drawing_wizard.xml',
        'wizard/create_invoice_advance.xml',
        'wizard/create_delivery_wizard.xml',
    ],
    'assets': {},
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
